### ISSUE TITLE
Uncaught TypeError: Cannot call a class as a function in version 0.14.1

### ISSUE THREAD

**Issue by lees** [dozoisch/react-google-recaptcha#105]
If you get a package with version 0.14.1 from npm you get this error.
It helps if you rebuild a package inside the node modules folder. My guess is that you forgot to rebuild 0.14.1 before publish it on npm.

**Comment by dozoisch** [comment]
Rebuild is handled by pre-publish script.

Can you tell me which version of react-async-script is install.

**Comment by hartzis** [comment]
just did a test install of `npm install react-google-recaptcha@0.14.1`.

it requests `"react-async-script": ">=0.11.0 < 1.0"` and installs:
`"version": "0.11.1"`

**Comment by lees** [comment]
^0.14.1

**Comment by dozoisch** [comment]
@lees version of react-async-script (which is a dependency) not recaptcha

**Comment by lees** [comment]
0.11.1

**Comment by CaitlinWeb** [comment]
@dozoisch @lees I encountered the same issue with `react-google-recaptcha@0.14.1` and `react-async-script@0.11.1`. Installing `react-google-recaptcha@0.14.0` and `react-async-script@0.11.0` fixed the error for me.

**Comment by ameem91** [comment]
I also saw this same issue and downgrading to `0.14.0` fixed the error.

**Comment by dozoisch** [comment]
@CaitlinWeb  @ameem91 @lees  Can you try to 0.14.2?

**Comment by lees** [comment]
> @CaitlinWeb @ameem91 @lees Can you try to 0.14.2?

It works! Thank you
