### ISSUE TITLE
React 0.14.0 warning 

### ISSUE THREAD

**Issue by bobiblazeski** [dozoisch/react-google-recaptcha#11]
Since React have been released I get warning
Warning: ReactDOMComponent: Do not access .getDOMNode() of a DOM node; instead, use the node directly. This DOM node was rendered by `reCAPTCHA`.

If I remove .getDOMNode() calls at lines 
https://github.com/bobiblazeski/react-google-recaptcha/blob/master/src/recaptcha.js
52 //     this.captcha.getDOMNode(); // removed
53 let id = this.props.grecaptcha.render(this.captcha, { // removed .getDOMNode() call
and rebuild I got

Warning: AsyncScriptLoader(...): React component classes must extend React.Component.warning @ 
main.js:1148 Uncaught Error: Invariant Violation: AsyncScriptLoader.render(): A valid ReactComponent must be returned. You may have returned undefined, an array or some other invalid object.

If I remove them at the compiled code components works without warning.

**Comment by dozoisch** [comment]
I should be able to get some time to update to react 0.14 this week

**Comment by bobiblazeski** [comment]
Works great many thanks.
