### ISSUE TITLE
Error: Couldn't find preset "es2015" relative to directory

### ISSUE THREAD

**Issue by Losapioj** [dozoisch/react-google-recaptcha#111]
Error message:

> error: bundling failed: Error: Couldn't find preset "es2015" relative to directory "[project directory removed for privacy]/node_modules/react-google-recaptcha"

I've tried `npm install babel-preset-es2015 --save` but to no avail. I'm attempting to use this code in a React Native application. the problem occurs when I import with `import ReCAPTCHA from 'react-google-recaptcha';`

I haven't gotten to the point of trying to use what i've imported

**Comment by dozoisch** [comment]
Can you try deleting the .babelrc in `node_modules/react-google-recaptcha`. I just noticed it is shipped and it probably shouldn't.

**Comment by hartzis** [comment]
nice catch @dozoisch should be an easy fix. just add to `.npmignore` and get a patch out?

**Comment by dozoisch** [comment]
@hartzis yeah I'll do that.

**Comment by dozoisch** [comment]
@Losapioj can you tell me if 1.0.4 solves this?

**Comment by Losapioj** [comment]
@dozoisch confirmed fixed!
