### ISSUE TITLE
expected a string or a class/function but got: object

### ISSUE THREAD

**Issue by charlesdagenais** [dozoisch/react-google-recaptcha#112]
I keep getting this error when adding the ReCAPTCHA component:

Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

Actually on React 16.4.2

```jsx
import ReCAPTCHA from 'react-google-recaptcha';
...
onCaptcha = (value)=>{
do something with value
}
...
render{
    return (
...
        <ReCAPTCHA onChange={this.onCaptcha} sitekey="TESTSITEKEY" />

...
)

}
```

**Comment by hartzis** [comment]
hey @charlesdagenais , are you able to make a codesandbox.io to replicate? And what version of `react-google-recaptcha`?

**Comment by charlesdagenais** [comment]
version 1.0.4
When using in codesandbox it's all working fine.

But on my development I'm using it in a Meteor(1.7)/React app. Always getting the same error. Something must go wrong on the building  phase...

**Comment by charlesdagenais** [comment]
Sorry! did a npm update on my project and problem solved. Anyway, thanks for the quick followup!
