### ISSUE TITLE
Related dependence (react-async-script 1.0.0)  not compatible with React 15.*

### ISSUE THREAD

**Issue by elhajouis** [dozoisch/react-google-recaptcha#115]
Hello,
We have the same issue, the dependencie react-google-recaptcha needs to download "react-async-script", on Windows it download the "react-async-script" version 0.10.0 or 0.11.1 (compatible with react 15.) but never higher => build OK delivrey OK.
However on linux, it always download the "react-async-script" version 1.0.0 which (not compatible with react 15.) => build OK with warning => delivrey KO (errors on the browser)
How can we bypass this problem without investing on a react upgrade?

Regards.

**Comment by dozoisch** [comment]
Use 0.14.2 instead of 1.0

**Comment by elhajouis** [comment]
Hello Hugo,

Thanks first for quick answer.
We can't force the download of the compatible version, all dependencies are atomatically downloaded and it retreives the version 1.0.0 which not working with react 15.*  .

Have you a porpose to force use the version 0.10.0 to 0.14.2. of react-async-script? 

From file package.json of react-google-recaptcha
![image](https://user-images.githubusercontent.com/39157292/46874266-aa8e3a80-ce30-11e8-8546-55f578fea0d8.png)
 
Regards.

**Comment by dozoisch** [comment]
@elhajouis in 1.0 we use new react apis. Which is also why there was a major version bump. The latest version compatible with the old version of react is 0.14.2. 

Also The package.json of 0.14.2 restricts react-async-script

![image](https://user-images.githubusercontent.com/4422516/46881996-14dbb680-ce02-11e8-9554-4672bb60085f.png)

https://unpkg.com/react-google-recaptcha@0.14.2/package.json


Also, if you can't specify version of dependencies.. I'm not sure what I can do. All the versions are tagged on both GitHub and NPM.

**Comment by elhajouis** [comment]
@dozoisch, thanks for the proposal, it should works.
Best regards.
