### ISSUE TITLE
A bit more help specifying the language?

### ISSUE THREAD

**Issue by cstaber** [dozoisch/react-google-recaptcha#117]
I have a component where I'm using the react-google-recaptcha and it works great, but I can't figure out how to change the language text. I tried this:

  componentWillMount() {
    window.recaptchaOptions = {
      lang: "ru"
    };
  }

...but that didn't work. Can you please provide a little more help on how I change the language? It'd be nice if it was just a prop on the component...

Thanks so much!

**Comment by dozoisch** [comment]
You need to define in before the Recaptcha component is imported. The easiest way is to define them directly on the page in a script.

Unfortunately can't really be a prop on the component at it is fairly static due to the way Google's script works.

**Comment by cstaber** [comment]
hmm I'm still struggling to get this to work. I'm using next.js and set it on componentDidMount in _document.js - which is as high up the chain as I can get it - and the component text still doesn't change. In the browser console, I can type window.recaptchaOptions and get {lang: "ru"} back - so I'm not sure. Do you have any suggestions?

**Comment by dozoisch** [comment]
It needs to happen before componentDidMount. try setting it in the script directly. outside of the component. It needs to defined before react, hence the settings are global on the windows object

**Comment by cstaber** [comment]
Got it - Thanks!

**Comment by mianusmankhalid** [comment]
@cstaber how did you try it, I am also using next.js but still figuring it out the place I need to put language option
