### ISSUE TITLE
Recaptcha not rendering

### ISSUE THREAD

**Issue by Rc85** [dozoisch/react-google-recaptcha#123]
react-google-recaptcha version: ^1.0.5

Sometimes the recaptcha renders an empty div. When it does renders the recaptcha and inspecting the code, the parent div has no attribute such as className='g-recaptcha' data-sitekey='xyz'.

**Comment by hartzis** [comment]
@Rc85 Thanks for the info.

Do you think you could create a codesandbox.io example that at also "sometimes" produces this behavior so we have something to work off of?

Can use the [example codesandbox.io](https://codesandbox.io/s/1y4zzjq37l) to start.

**Comment by wcpaez** [comment]
@Rc85 This happened to me when I loaded the <script src='https://www.google.com/recaptcha/api.js'></script> on head. It is not necesary
