### ISSUE TITLE
How to run automation tests on a page with react-google-recaptcha

### ISSUE THREAD

**Issue by grantspilsbury** [dozoisch/react-google-recaptcha#125]
react-google-recaptcha version: 1.0.5

Hi, thanks for the library. I have a react app that's using recaptcha. I have added the Google test site key. How can I run automated tests that require the recaptcha to be completed before a form can be submitted? Is there a way to bypass it or simulate a click using selenium?

**Comment by jeanpaulangelle-taulia** [comment]
Hey @grantspilsbury. Did you figure it out? I am stuck on this as well. Using Jest.
