### ISSUE TITLE
Updating state

### ISSUE THREAD

**Issue by vQFire** [dozoisch/react-google-recaptcha#126]
react-google-recaptcha version: 1.0.5

I am using the recaptcha (obviously) But I want it to change sizes depending on screen size. I have tried the following:  

Adding the event:
```
componentDidMount () {
    window.addEventListener('resize', () => {
        if (window.innerWidth < 641) {
            this.setState({ captchaSize: 'compact' })
        } else {
           this.setState({ captchaSize: 'normal' })
       }
    })
  }
```
The Component:
```
<ReCAPTCHA size={this.state.captchaSize} ref='recaptcha' sitekey={this.siteKey} onChange={this.updateRecaptcha} />
```

I have checked and the state does change. Only now the recaptcha does not update when a new state is given  

Please help!

**Comment by dozoisch** [comment]
The size is utilized on the first render, due to the imperative google API.

The easiest to get that to work would be to pass a `key` properties, that you change with the size (could even be the size itself), which will cause the component to unmount and remount.
