### ISSUE TITLE
Custom style for CAPTCHA challenge prompt

### ISSUE THREAD

**Issue by SuhanKoh** [dozoisch/react-google-recaptcha#131]
react-google-recaptcha version: 1.0.5

Is there a way to customize the styling the iframe div block? I have a global theme blur running and it is messing with the challenge prompt..

**Comment by javadhamidi** [comment]
hello there's

**Comment by dozoisch** [comment]
@SuhanKoh If ReCAPTCHA supports it, then we can add something otherwise I doubt we can do much.

**Comment by SuhanKoh** [comment]
After investigating official recaptcha doc, doesn't seems to have a way. Did some work around.
