### ISSUE TITLE
Getting error "reCAPTCHA client has been deleted: 0"

### ISSUE THREAD

**Issue by RishabhTayal** [dozoisch/react-google-recaptcha#135]
react-google-recaptcha version: 1.0.4
react-async-script version: 1.0.0

We were using Google recaptcha but today suddenly started seeing the above-mentioned error. Did something recently changed on the Google side.

Is anyone else having this issue?

**Comment by hartzis** [comment]
appears to be google recaptcha script related issue, as there is a similar issue here: https://github.com/DethAriel/ng-recaptcha/issues/136

maybe try updating/refreshing your recaptcha sitekey?

**Comment by RishabhTayal** [comment]
@hartzis I have tried updating the recaptcha key. It doesn't work. Still getting same error.

**Comment by Bigdeeua** [comment]
For react library the same, until that moment everything was fine

**Comment by hartzis** [comment]
@RishabhTayal do you think you could try to recreate your scenario using a (codesandbox)[https://codesandbox.io/s/1y4zzjq37l]?

**Comment by Bigdeeua** [comment]
In general, when I use a component from a recaptcha, I cannot change it to another one later, I always get the error "reCAPTCHA client has been deleted: 0", which is the strangest thing, everything was good before

**Comment by Bigdeeua** [comment]
@RishabhTayal Man, use the "react-recaptcha", this forking fine

**Comment by aaronvanston** [comment]
We are seeing the exact same issue, according to our logs this started happening approximately 22 hours ago (14:54 AEST). 

This component itself causes the entirety of react to dismount. As a stop-gap solution, we are wrapping the reCaptcha library in a react error boundary, which prevents the dismount and white screen but will still throw the error silently. With this inplace, the captcha still works and you can navigate away.

**Comment by zacanger** [comment]
We use both this library and a similar one depending on the app, and for us wrapping in an error boundary also helped. Hopefully this is a bug Google fixes soon.

**Comment by Bigdeeua** [comment]
The error disappeared by itself after some time
