### ISSUE TITLE
Can't add event listener (key down) after submitting the captcha

### ISSUE THREAD

**Issue by max-glyzin** [dozoisch/react-google-recaptcha#136]
react-google-recaptcha version: 1.0.5
react-async-script version: 1.0.1

I render recaptcha in my component

```
 <ReCAPTCHA
     sitekey="sadfsdfsadfasdfUqhEHvqxYO4UJeompXDkua"
     onChange={this.handleCaptcha}
 />
```

and want to add the window event listener for Enter key. I want this for accessibility (submitting of form)

```
 componentDidMount() {
    window.addEventListener('keydown', function(e) {
      console.log(e);
    })
  }
```

this is my handleCaptcha method

```
handleCaptcha = value => {
    this.setState({ captcha: value })
}

```
But the problem is that I can't catch any event after captcha was submited. I have no idea what to do.

**Comment by dozoisch** [comment]
What do you mean by catch any event?

Key down events on the page/form are not being propagated after catpcha has been submitted?

**Comment by max-glyzin** [comment]
Yes. After submitting key events are not propagated. But If I click on the page (component) with form I can see them in the console (events propagated). I think this is the problem with focusing on the captcha iframe, but when I click on form focus back on the window and everything work fine. 
So I tried using refs to focus back on the window and component, but that's not working.

**Comment by max-glyzin** [comment]
Sorry for quality of the gif
![out](https://user-images.githubusercontent.com/48626144/57272029-30165800-70ab-11e9-8e4b-66ee342a160f.gif)

**Comment by dozoisch** [comment]
@max-glyzin could it be that the focus is on the google captcha div and google captcha is preventing propagation? try adding the event handler in the capture phase instead of bubbling to see if it makes a difference.

**Comment by max-glyzin** [comment]
I was able to solve the problem with setTimeout. Because for the sake of experiment I've focused not on the window, but on the input and have seen that cursor focus on it and then suddenly disappear.

```
componentDidUpdate() {
    if (this.state.fields.captcha.value) {
      setTimeout(() => {
        window.focus()
      }, 1000);
    }
  }
```
@dozoisch what do you think?

**Comment by max-glyzin** [comment]
Okay, I understand that you think none. Close the issue, please.

**Comment by dozoisch** [comment]
@max-glyzin it really seems to be due to an issue with ReCaptcha capturing all the events, which unfortunately we don't have control over, given that ReCaptcha itself is implemented by Google.

**Comment by max-glyzin** [comment]
@dozoisch  this problem will face any individual who will want to create the accessible form in react. So I think that this information will be useful. I just want to know the correct way of solving this problem.

**Comment by max-glyzin** [comment]
Anyway thanks for answer, I appreciate it.

**Comment by dozoisch** [comment]
@max-glyzin I unfortunately don't know the correct way to deal with this. What I assume is that if you use the capture parameter of the event handler 

```
target.addEventListener(type, listener[, useCapture]);

// like this;
window.addEventListener('keydown', function(e) {
    console.log(e);
}, true);
```

Might help you get the handlers without google interfering. Otherwise I think you "manual" refocus of the window, might be the way to go.

**Comment by max-glyzin** [comment]
@dozoisch man, you are right! I've tried  addEventListener with TRUE as the third parameter and form is working without componentDidUpdate method. It's like magic, thanks. But I still don't understand underlying mechanism of this.

**Comment by dozoisch** [comment]
@max-glyzin see https://stackoverflow.com/a/22164614/1452289

when you click (or generate any event) on something in a browser, it goes through 2 phases. Capture and Bubbling.

Capture starts from the outer most piece (document / body) and goes through the HTML tree down to your element, letting any handlers do something with the event. When it hits the target element (eg: a button) it starts bubbling back up, using the same route.

Given that capture goes first, you get access to the event before anyone else is able to stop the propagation. If you register on document on the bubbling phase, you will be the last handler to receive the event and thus lets a lot of "time" for other handlers to block the event. By using a document handler on capture phase you are the very first handler to receive the event.

**Comment by max-glyzin** [comment]
@dozoisch thanks for explanation. Now I understand how this parameter works.
