### ISSUE TITLE
"We detected that your site is not verifying reCAPTCHA solutions."

### ISSUE THREAD

**Issue by cneuro** [dozoisch/react-google-recaptcha#145]
react-google-recaptcha version: 1.1.0
react-async-script version: 1.1.1

This message appears on my Google reCAPTCHA dashboard. As far as I understand, this particular package has no need to define a POST callback for any backend verification.

```javascript
<ReCAPTCHA
  ref={this.reCaptchaRef}
  size="invisible"
  sitekey={CAPTCHA_SITEKEY}
  onChange={captchaVal => this.handleCaptcha({ captchaVal })}
  onErrored={() => this.handleCaptcha()}
/>
```

When calling `this.reCaptchaRef.current.execute()`, all the necessary (non-manipulable) verification is done on the component level, correct? Am I missing something? How do I get rid of this error message?

Thanks!

**Comment by dozoisch** [comment]
@cneuro once you retrieve the captchaVal you should send it to your server and your server should verify that the captcha value is valid. 

https://developers.google.com/recaptcha/docs/verify#api-request

**Comment by cneuro** [comment]
@dozoisch thanks for your reply!

But why is this extra backend validation needed in this case? Why is it not sufficient to assume the user has successfully passed the challenge in the `onChange` method? Is it somehow possible to call that component method externally without having solved the challenge legitimately?

**Comment by dozoisch** [comment]
@cneuro the reason you need to validate the token in the backend is that anyone could call your api directly without using your UI. And so if you don't validate the token from the backend I can pass any information in that token and create fake users if I want to, defeating the purposes of a captcha.

**Comment by cneuro** [comment]
Thanks for your reply, @dozoisch. Forgive my ignorance, and thank you very much for your time.

The reason I'm confused is because I don't understand how it's possible to call the `onChange` of the `<ReCAPTCHA />` component without actually having solved the captcha. I was assuming that this callback simply guarantees that the captcha was solved properly, as it states that it is "The function to be called when the user successfully completes the captcha".

Assuming the secret call to Google's `siteverify` is _not_ done, how can a malicious user spoof a successfully-solved captcha with this library?

**Comment by dozoisch** [comment]
@cneuro you are right about the fact that ReCaptcha itself can't be spoofed. 

The thing is when ReCaptcha is solved and the user submits the form, you do a network request (with fetch or xhr). This network request can be spoofed with something like cURL or any http client. I don't need to use your UI to interact with your backend.

Given that, I can then spoof a fake value for the token when calling your backend, opening the door to robots.

**Comment by bogdancss** [comment]
just noticed this when integrating this package in our project - as you mentioned, it would be a good idea to mention this somewhere in the README
