### ISSUE TITLE
issue while resetting the recaptcha

### ISSUE THREAD

**Issue by krnbr** [dozoisch/react-google-recaptcha#147]
react-google-recaptcha version: 2.0.0-rc.1
react-async-script version: 1.1.1

I am having an issue while resetting the recaptcha

I am using a functional component

extracts of code as below

```
// imports etc.. here
const Login: NextPage = (props:any) => {

// othere initializations here...

const recaptchaInputRef:any = React.createRef();

const handleSubmit = async (event) => {

      // some if condition
     // and else
     // and inside there
     recaptchaInputRef.current.reset();

}

return (
        <React.Fragment>

               <form onSubmit={e => handleSubmit(e)}>

               // other components and elements

              <ReCAPTCHA
                 ref={recaptchaInputRef}
                 sitekey={props.recaptchaKey}
                 onChange={ onChange }
                 onExpired={ onExpired }
                 />

              <Button type="submit">Sign In</Button>
              </form>
        </React.Fragment>
);

```

now the issue is that i get - Cannot read property 'reset' of null for the code -> `recaptchaInputRef.current.reset();`

**Comment by krnbr** [comment]
ok good news, I was able to resolve it using reacts hooks kind of reference initialization as below

```
const recaptchaInputRef:any = useRef({});
```

and it worked awesomely

**Comment by leopucci** [comment]
Any javascript version? I could not run this code

**Comment by leopucci** [comment]
This error is happenng when using executeAsync. 
I thin that reset is not available while using async but this is not documented
