### ISSUE TITLE
role= presentation on label

### ISSUE THREAD

**Issue by kendallgassner** [dozoisch/react-google-recaptcha#148]
on recaptcha-anchor-label you have a role presentation

react-google-recaptcha version: 2.0.0-rc.1
react-async-script version: x.x.x

**Comment by dozoisch** [comment]
Hi, I'm not totally sure what you mean, could describe it a little better?

**Comment by kendallgassner** [comment]
the recaptcha label 'I'm not a robot' has the role 'presentation'.

![Screen Shot 2019-08-20 at 10 53 03 AM](https://user-images.githubusercontent.com/15275462/63371317-b6903600-c338-11e9-9982-c4a58756e9e7.png)

I do not think you want to add that role for a label. 

https://www.w3.org/TR/wai-aria-practices-1.1/#presentation_role

<img width="638" alt="Screen Shot 2019-08-20 at 11 01 59 AM" src="https://user-images.githubusercontent.com/15275462/63372006-11765d00-c33a-11e9-9ace-0ec13fce9a50.png">

**Comment by dozoisch** [comment]
Hi Kendall, that really seems to be in the markup generated by Google. Unfortunately don't have much control over this as this is just a thin wrapper over Google's ReCaptcha scripts.
