### ISSUE TITLE
Changing theme programmatically

### ISSUE THREAD

**Issue by b-b0t** [dozoisch/react-google-recaptcha#149]
As stated above is it possible to change the dark / light theme on function call or similiar. Looking to implement new `prefers-color-scheme` media query.

react-google-recaptcha version: 2.0.0-rc.1

**Comment by dozoisch** [comment]
@b-b0t if Google ReCaptcha supports it we can support it otherwise, not much we can do as the markup is generated by Google's script

**Comment by b-b0t** [comment]
@dozoisch thanks for the response. would this only be possible by remounting the component? ie. if i wanted a transition without refresh.

**Comment by dozoisch** [comment]
@b-b0t to easily have the component unmount and remount all you have to do is set a different key on it so like you could use the theme as the key. ReCaptcha needs to remount though as it only does the render at mount time as of now.

**Comment by b-b0t** [comment]
the only problem is to check for dark mode I need to access either `window` to check for html appended class or `localStorage` to retrieve a `dark-mode` value I append on theme switch. This means I can only use the `componentDidMount` lifecycle method which only fires once.

I would need something that could dynamically inject the theme string when either of the above values changes. Here is my `Captcha.jsx` component:

```
import React, { Component } from 'react';
import ReCAPTCHA from 'react-google-recaptcha';

export default class Captcha extends Component {
  constructor(props) {
    super(props);
    this.state = {
      theme: 'light',
    };
  }

  componentDidMount() {
    const darkmode = document.querySelector('html').classList.contains('dark');
    if (darkmode) {
      this.setState({ theme: 'dark' });
    } else {
      this.setState({ theme: 'light' });
    }
  }

  render() {
    return <ReCAPTCHA theme={this.state.theme} />;
  }
}
```

**Comment by b-b0t** [comment]
Awesome thanks for the help man, went with a different solution as that still had a delayed rendering. Ended up rendering both and hiding / displaying depending on body class. The swop-out is instant now.
