### ISSUE TITLE
Source does not build in Windows

### ISSUE THREAD

**Issue by weiluntong** [dozoisch/react-google-recaptcha#151]
react-google-recaptcha version: 2.0.0-rc.1
react-async-script version: 1.1.1

The source code does not build in Windows because of a discrepancy in how environment variables are set.

My solution is to add "cross-env" to development dependencies and prefix scripts that set `BABEL_ENV` (such as "test" and "build:esm") with "cross-env".

I've tested this on both Windows and Ubuntu:
Windows 1903
Node 12.1.0

Ubuntu 19.04
Node 12.10.1

Both build and test ran successfully. Can I make a PR for this?

**Comment by dozoisch** [comment]
@weiluntong yep if you have time, I'll be more than happy to review a PR
