### ISSUE TITLE
Content Security Policy

### ISSUE THREAD

**Issue by nimahkh** [dozoisch/react-google-recaptcha#155]
hello guys , when i use Recaptcha , fire fox shows warnings below :
```
Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified
```

**Comment by hartzis** [comment]
Hrrmm, Yeah i'm seeing them on the [demo](https://codesandbox.io/s/1y4zzjq37l) in firefox. I don't know what they mean though. Need to do some research.

**Comment by phthhieu** [comment]
@hartzis Any update on this?

**Comment by LeComptoirDesPharmacies** [comment]
Same here

**Comment by hartzis** [comment]
@LeComptoirDesPharmacies Thanks for the poke, but i haven't been able to find any real info on this 

I'm goign to close this issue for now.

We can absolutely open this back up if it is causing a real issue or a bug.

Additionally, I'd wager this is coming from google recaptcha itself and there is nothing this package can do and the issue should actually be filed with [google recaptcha issues](https://github.com/google/recaptcha/issues).
