### ISSUE TITLE
Recaptcha Change Lang on Props change

### ISSUE THREAD

**Issue by ulisescarreonalvarez** [dozoisch/react-google-recaptcha#156]
react-google-recaptcha version: 2.0.1

Hi everyone,

I need to change the Recaptcha Lang when receive some new props with `getDerivedStateFromProps`, but when i use the code like:

```
  <ReCAPTCHA
                  hl={this.langSelectedCode}
                  ref={(r) => this.recaptcha = r}
                  sitekey="6Lfw0rIUAAAAALa-KpF_84u6TVvML7BW8QWsPfx0"
                  onChange={this.handleCaptchaResponseChange}
                />
```

But the lang doesn't not change, i read some advices but doesn't work like expected like setting a `key` and just adding ++ on the componentDidUpdate but i think thats not the righr way.
 Any advice?

**Comment by dozoisch** [comment]
@ulisescarreonalvarez the render is only done at mount time right now, but you can work around this by forcing a remount.

To do this, you can add  `key={this.langSelectedCode}` as prop and it'll force unmount and remount when you change the language

**Comment by ulisescarreonalvarez** [comment]
Hi @dozoisch,
 I put the key based on the langSelectedCode of the state, and it works!!

Thanks a lot.
