### ISSUE TITLE
export 'default' (imported as 'React') was not found in 'react', when using Preact

### ISSUE THREAD

**Issue by peterswallow** [dozoisch/react-google-recaptcha#158]
react-google-recaptcha version: 2.0.1
react-async-script version: 0.11.1

I'm using react-google-recaptcha within a preact.js website. It was working fine with Preact.js v8 (equiv to React v15) and react-google-recaptcha v0.12.0.

But we just upgraded to Preact v10 (equivalent to React v16) and react-google-recaptcha v2.0.1 and we've started getting this error:

`WARNING in ./node_modules/react-google-recaptcha/lib/esm/recaptcha.js 164:2-7 `
`"export 'default' (imported as 'React') was not found in 'react'`
`@ ./node_modules/react-google-recaptcha/lib/esm/index.js `

I suspect this is because Preact v10 has removed the `export default` from its core as mentioned here https://preactjs.com/guide/v10/upgrade-guide

`To better support tree-shaking we don't ship with a default export in preact core anymore. The advantage of this approach is that only the code you need will be included in your bundle.`

As the `recaptcha.js` file imports
`import React from "react";`
and then tries to resolve `React.Component` like
`export default class ReCAPTCHA extends React.Component {`
it fails.

So I think we need to update the import in `recaptcha.js` from
`import React from "react";`
to
`import {Component} from "react";`
and the extends from
'export default class ReCAPTCHA extends React.Component {`
to
`export default class ReCAPTCHA extends Component {`

Does this sound right?

**Comment by hartzis** [comment]
@peterswallow This is interesting.

There may also be something about the default import for `React` and `jsx` and the babel presets `@babel/react` that we need to look into.

If you can find any clarifying information on this that would be awesome. thanks.

**Comment by hartzis** [comment]
@peterswallow Can you try the new alpha to see if this approach fixed this issue?

https://www.npmjs.com/package/react-google-recaptcha/v/2.1.1-alpha.1

I've verified the react import change doesn't break the package via codesandbox.
- https://codesandbox.io/s/eloquent-sammet-83wth?file=/src/index.js
- https://codesandbox.io/s/react-google-recaptcha-210-example-invisible-qv8m7?file=/src/index.js
