### ISSUE TITLE
Uncaught Error: ReCAPTCHA placeholder element must be empty

### ISSUE THREAD

**Issue by dfala** [dozoisch/react-google-recaptcha#16]
That error is everywhere. Maybe I'm using it wrong?

**Comment by zimok** [comment]
Started happening to me as well since yesterday. It seems that it's caused by double-rendering. 
Calling `grecaptcha.reset()` somewhere should fix, but I have to figure it out.

**Comment by bobiblazeski** [comment]
Started happening to me too.

**Comment by dozoisch** [comment]
Is that happening on 0.5 or 0.5.1? One issue was caused by the fact that id now start at 0.

**Comment by bobiblazeski** [comment]
No error on 0.5.1, many thanks

**Comment by dfala** [comment]
Same here, thanks! - close issue?

**Comment by dozoisch** [comment]
cool! Let me know if it shows up again!

**Comment by elduderino87** [comment]
Is it at all possible to fix this for 0.4/react 1.3? We are unable to upgrade our react since a whole lot of other components break. Would be great if a fix would be sneaked in for 0.4 ;)

**Comment by dozoisch** [comment]
@elduderino87 I'll see what I can do!

**Comment by dozoisch** [comment]
@elduderino87 I published v0.4.1 to npm, let me know if it works!

**Comment by elduderino87** [comment]
@dozoisch That does it, thanks for the quick help and the great component :+1:

**Comment by rontornambe** [comment]
This error just started happening to me on 6/14/2016. I thought the latest version of reCaptcha was 2.0. Of what software is 0.5.1?

**Comment by dozoisch** [comment]
@rontornambe google reCaptcha is 2.0 

react-google-recaptcha that is a react component to print a captcha is version 0.5.1
