### ISSUE TITLE
Recaptcha Sometimes says Invalid site key... (initial renders) 

### ISSUE THREAD

**Issue by meadow-tulips** [dozoisch/react-google-recaptcha#165]
```
import React from 'react'
import ReCAPTCHA from 'react-google-recaptcha'

const Recaptcha = ({ _reCaptchaKey, onChange, theme, size }) => {
  return (
    <ReCAPTCHA
      sitekey={_reCaptchaKey}
      onChange={onChange}
      theme={theme}
      size={size}
    />
  )
}

Recaptcha.defaultProps = {
  _reCaptchaKey: 'siteKey',
  theme: 'light',
  size: 'normal',
}

export default Recaptcha
```

Here lies my ReCaptcha wrapper. The _reCaptchaKey is passed from an API call coming from a Provider which probably takes some time after the initial render.

The trouble is sometimes the component renders with saying invalid site key and upon refreshing the page couple of times it loads the checkbox with the same key credential. My understanding is that on change of _reCaptchaKey props the component is not re rendering. Sometimes if the DOM is painted after the api call results I can see the checkbox but most often not. 

I am also not sure if I am rendering this  the correct way. 

Any help would be much appreciated.

**Comment by dozoisch** [comment]
When you don't have the proper key for the API you should probably avoid rendering the component.


```
const Recaptcha = ({ _reCaptchaKey, onChange, theme, size }) => {
  if (!_reCaptchaKey) { return null; }
  return (
    <ReCAPTCHA
      sitekey={_reCaptchaKey}
      onChange={onChange}
      theme={theme}
      size={size}
    />
  )
}
```
