### ISSUE TITLE
Link to deps is broken

### ISSUE THREAD

**Issue by etienne-bondot** [dozoisch/react-google-recaptcha#175]
Hi,
This is just a little issue on the README. The top link to dependencies is broken see [here](https://david-dm.org/dozoisch/react-google-recaptcha).

**Comment by hartzis** [comment]
Yeah. Looks like the service has been a [hit or miss recently](https://github.com/alanshaw/david/issues/163)

david dependency service/badge - https://github.com/alanshaw/david

Maybe we just remove it as a badge?

**Comment by etienne-bondot** [comment]
The link is up again. I close this issue.
