### ISSUE TITLE
CDN for react-goole-recaptch

### ISSUE THREAD

**Issue by programwithus** [dozoisch/react-google-recaptcha#178]
Hello Everyone,

I have tried to use react-google-recaptcha as CDN.

My HTML

```
<script src="https://cdn.jsdelivr.net/npm/react-google-recaptcha@2.1.0/lib/index.min.js"></script>
<script
      src="https://www.google.com/recaptcha/api.js?onload=onloadCallback&render=explicit"
      async
      defer
></script>
```

My React Components

```
function onChange(value) {
  console.log("Captcha value:", value);
}
 
ReactDOM.render(
  <ReCAPTCHA
    sitekey="Your client site key"
    onChange={onChange}
  />,
  document.body
);
```

And I got Error message React component is not defined. Apparently it does not see my ReCAPTCHA component.

As far as I know there are two libraries react-recaptcha and react-google-recaptcha. I tried them both as CDNs did not work and I got the same Error. I have added React components to my existing project and cannot install them wit npm.

Please let me know if you had similar experience.

All the Best and thank you.

**Comment by hartzis** [comment]
Sadly @programwithus we currently do not officially support or supply a CDN hosted build of this package.

This relates to #190 and setting up a possible UMD build of this package.

Closing for now and linking to #190
