### ISSUE TITLE
Case Exit google recaptcha

### ISSUE THREAD

**Issue by IRediTOTO** [dozoisch/react-google-recaptcha#180]
react-google-recaptcha version: newest
react-async-script version: newest
Hi, can we catch event onExit ? If you user didn't solve the captcha?

![image](https://user-images.githubusercontent.com/15695252/86356452-7a3a9f80-bc96-11ea-864d-0803b7725451.png)

**Comment by hartzis** [comment]
Hello @IRediTOTO appreciate you taking the time to file an issue.

I'm having trouble trying to understand exactly the issue. The screenshot doesn't show anything that i can tell.

Could you possibly make a [https://codesandbox.io/](https://codesandbox.io/) example that demonstrates the issue, please?

**Comment by IRediTOTO** [comment]
Oh, its a gif. Ok I will do later

**Comment by Sajarin-M** [comment]
> I'm having trouble trying to understand exactly the issue.

@hartzis Apologies for reopening,
I'm facing the same issue. The `executeAsync()` call doesn't resolve or reject when the user closes the recaptcha verification modal by clicking outside.
Is there a way to detect if the modal was closed?

Here is the [Codesandbox](https://codesandbox.io/s/react-google-recaptcha-promise-6rmn79)
Please make sure the CAPTCHA modal is displayed.

Also, here's a video

[video.webm](https://github.com/dozoisch/react-google-recaptcha/assets/68892162/36a169f1-a10e-465b-b124-7ed5eed53f46)

**Comment by ryants51** [comment]
I am also experiencing this issue. Basically, I can always know when the user starts ReCAPTCHA, but I can't always know when it is "finished" if the user exits the ReCAPTCHA. Whenever there is an error or the user completes it, I can know, but not when the user bails from it.
