### ISSUE TITLE
We detected that your site is not verifying reCAPTCHA solutions. This is required for the proper use of reCAPTCHA on your site.

### ISSUE THREAD

**Issue by oliverox** [dozoisch/react-google-recaptcha#183]
react-google-recaptcha version: 2.1.0
react-async-script version: 1.1.1

I keep seeing the message: "We detected that your site is not verifying reCAPTCHA solutions. This is required for the proper use of reCAPTCHA on your site." in the google developer console after using react-google-recaptcha. I assumed the package should be handling this for me. Is that not the case?

**Comment by dozoisch** [comment]
You have to validate the token on your server once you get it back. This only handles the client side of things

**Comment by oliverox** [comment]
Got it. Thank you!
