### ISSUE TITLE
reset(); not working

### ISSUE THREAD

**Issue by iulixxi** [dozoisch/react-google-recaptcha#189]
react-google-recaptcha version: 2.1.0
react-async-script version: 1.1.1

Hi,

guys I have a problem and I can't get to the bottom of this...

I am currently using the `react-google-recaptcha` v2.1.0 on my project and, for some reason, the `https://www.google.com/recaptcha/api2/reload?XXX` call goes through ONLY for the first time...
If for various reasons I am trying to reset the recaptha - via `recaptcha.current.reset();` or even `window.grecaptcha.reset();` my `/reload` POST doesn't even show up in my network tab.
All my functions are in my window.grecaptcha and I can call each and everyone via console, no errors or anything, but when I am trying to reset it it doesn't make the `/reload` post...

Any thoughts?
Thanks!
E

**Comment by iulixxi** [comment]
Clarification: the reset(); doesn't work at all... the first post on the `reload` is don onload...

**Comment by hartzis** [comment]
@iulixxi thank you for the issue and explanation.

I don't know what calls or what exactly google recaptcha does internally for `reset`.

Their documentation does not tell us much.
- https://developers.google.com/recaptcha/docs/display#js_api

We have verified via tests that `react-google-recaptcha` is calling the `reset` method on `grecaptcha` properly, but that is were our interface ends with google recaptcha.
https://github.com/dozoisch/react-google-recaptcha/blob/3ef5bc9df6ff6a08ea5c8f195d4c1be7a9ba56af/test/recaptcha.spec.js#L56-L57

This may be a great issue for google recaptcha itself. And i may suggest filing an issue with them? Could provide them with a codesandbox.io example too that could help them narrow down the issue you're seeing.

https://github.com/google/recaptcha/issues

**Comment by hartzis** [comment]
📓 An aside if you're trying to call `window.grecaptcha.reset();` directly yourself on a recaptcha generated by `react-google-recaptcha` you need the `widgetId` for the `reset` call.
- you can retrieve the `widgetId` from the `react-google-recaptcha` ref/instance via `getWidgetId()`
```

**Comment by iulixxi** [comment]
Thanks for the reply!

I'll dig deeper into this...

**Comment by iulixxi** [comment]
Small update: Have't done a single code change and it started working again (note: this was working fine when we thoroughly tested this a few months back)...

Thanks Google... I guess...

**Comment by hartzis** [comment]
Glad to hear it started working again, and yes, "thanks google" is in order. 🤣 . Closing the issue, thank you again for reaching out and starting a conversation that may be helpful to others too.

**Comment by FabioZan86** [comment]
@iulixxi Hello. Does the problem with captcha reset still exist?

**Comment by iulixxi** [comment]
Nop, all good! Ty

**Comment by FabioZan86** [comment]
@iulixxi All good. I found an alternative solution: 
```
declare global {
  interface Window {
    grecaptcha: {
      reset: (widgetId?: number | string) => void;
    };
  }
}

let recaptchaRef: ReCAPTCHA | null = null; // Ref

export const resetCaptcha = () => {
  if (recaptchaRef) {
    recaptchaRef.reset(); // not work
    const widgetId = recaptchaRef.getWidgetId();
    if (widgetId) {
      //window.recaptchaRef.reset(widgetId); // not work
      //window.grecaptcha.reset(widgetId);  // not work
      window.grecaptcha.reset();  // worked
    }
  }
};

 <ReCAPTCHA
        ref={(ref) => (recaptchaRef = ref)}
        sitekey={process.env.NEXT_PUBLIC_GOOGLE_CAPTCHA_SITE_KEY!}
        onChange={handleCaptchaChange}
      />
```

Honestly, I don't understand why it didn't work: `window.grecaptcha.reset(widgetId);  // not work`
