### ISSUE TITLE
How to reset captcha

### ISSUE THREAD

**Issue by gmarquesetr** [dozoisch/react-google-recaptcha#21]
How can I reset the captcha?

I'm render it like these:
`<ReCAPTCHA
   ref="recaptcha"
   sitekey="xxxxxxxxx"
   onChange={this.onCaptchaChange} />`

I know I can do something like grecaptcha.reset() but I can't understand how I do this:

> var grecaptchaObject = grecaptcha // You must provide access to the google grecaptcha object.

Thank you :)

**Comment by dozoisch** [comment]
Hi! if you have a ref on the component you can do

`this.refs.recaptcha.reset()`

The function is exposed! See https://github.com/dozoisch/react-google-recaptcha#component-api
