### ISSUE TITLE
Warning: 

### ISSUE THREAD

**Issue by miinx** [dozoisch/react-google-recaptcha#22]
Hi there,

Changes in [React 15.2.0](https://github.com/facebook/react/releases/tag/v15.2.0) mean you'll get a warning now for unknown properties on DOM elements. 

`react-google-recaptcha` is triggering one for `grecaptcha` in the `div` it creates:

<img width="946" alt="screen shot 2016-07-18 at 2 19 13 pm" src="https://cloud.githubusercontent.com/assets/1623076/16906026/2604bf84-4cf3-11e6-987a-324f64c80502.png">

In the above, our `SignInForm` contains:
`import ReCAPTCHA from 'react-google-recaptcha'`

Cheers
Karen

**Comment by dozoisch** [comment]
Oh, yeah! Thanks for reporting, I'll try to cut a release today.

**Comment by dozoisch** [comment]
@miinx released 0.5.4! Let me know.
