### ISSUE TITLE
How to checkCaptcha?

### ISSUE THREAD

**Issue by vgoklani** [dozoisch/react-google-recaptcha#23]
I used your function:

	checkCaptcha: function(value) {
		console.log("Captcha value:", value);
	},

But what do I do with this value? Is it the case that this function will only be called with the user is not a robot? What should we do with this value hash?

**Comment by dozoisch** [comment]
Hello!

As stated in [reCaptcha docs](https://developers.google.com/recaptcha/docs/verify#api-request) you need to send this value to your server. Once you receive the value from the server you do an api call to https://www.google.com/recaptcha/api/siteverify with your secret and the value you got from the user.
