### ISSUE TITLE
'No overload matches this call.' - React + Typescript

### ISSUE THREAD

**Issue by jonasmarco** [dozoisch/react-google-recaptcha#230]
react-google-recaptcha version: 2.1.0

Hi guys, I'm having a problem with the 'ref' I'm using TypeScript in my project, and when creating a ref and using it in <ReCAPTCHA> I get the following error.

TS2769: No overload matches this call. Overload 1 of 2, '(props: Readonly<ReCAPTCHAProps>): ReCAPTCHA', gave the following error. Type 'RefObject<unknown>' is not assignable to type 'LegacyRef<ReCAPTCHA> | undefined'. Type 'RefObject<unknown>' is not assignable to type 'RefObject<ReCAPTCHA>'. Type 'unknown' is not assignable to type 'ReCAPTCHA'. Overload 2 of 2, '(props: ReCAPTCHAProps, context?: any): ReCAPTCHA', gave the following error. Type 'RefObject<unknown>' is not assignable to type 'LegacyRef<ReCAPTCHA> | undefined'.

My code

`
    const recaptchaRef = createRef<HTMLDivElement>();
`
`
    return (
        <ReCAPTCHA
           ref={recaptchaRef}
           sitekey='sitekey'
           onChange={onCaptchaChange}
           size='normal'
        />
)
`

**Comment by eatmoarrice** [comment]
Try:

```
const recaptchaRef: any = React.createRef();
```

**Comment by liqwiz** [comment]
```js
// ReCAPTCHA takes LegacyRef type
const recaptchaRef = createRef<ReCAPTCHA>()
```

**Comment by jonasmarco** [comment]
tnk u guys

**Comment by dkhierl-chacrasoftware** [comment]
> ```js
> const recaptchaRef = React.createRef<ReCAPTCHA>()
> ```

this seem not working for me anymore

**Comment by jlison** [comment]
Recently I needed to use:
```typescript
  const recaptchaRef =  React.createRef<ReCAPTCHA & HTMLDivElement>();
```
in order to avoid a type error.

**Comment by Damian-Ogrodnik** [comment]
You can try: 
```tsx
  const recaptchaRef = useRef<ReCAPTCHA>(null);
```

**Comment by dorklord23** [comment]
For the latest solution, use this:

```ts
const recaptchaRef = useRef<ReCAPTCHA>(null);
```
