### ISSUE TITLE
Not working on Android/iOS

### ISSUE THREAD

**Issue by brsnik** [dozoisch/react-google-recaptcha#240]
react-google-recaptcha version: v2.1.0
react-async-script version: Y.Y.Y

I am getting the `onErrored` method called right from the page load on Android and iOS. 

[![enter image description here][1]][1]

Works fine on PC/Mac.

------------

Setting the ref:

      constructor(props) {
        super(props);
        this.captchaRef = React.createRef();
      }

On error:

      handleCaptchaError = (event) => {
        console.log("handleCaptchaError", { event });
      };

On submit:

      handleSubmit = async (form) => {
    
        form.preventDefault();
    
        this.captchaRef.current.reset();
    
        const token = await this.captchaRef.current.executeAsync();
    
        const { email, password } = form.target.elements;
    
        if (this.handleEmail(email.value) && this.handlePassword(password.value)) {
          this.props.dispatch(
            authorize({
              email: email.value,
              password: password.value,
              captcha: token,
            })
          );
        }
      };

The form:

    render() {
        return (
          <React.Fragment>
            <Form onSubmit={this.handleSubmit}>
              
              <List>
                <ItemInput>
                  <Input
                    type="email"
                    name="email"
                    autoComplete="username"
                    onChange={(e) => this.handleEmail(e.target.value)}
                  ></Input>
                </ItemInput>
                <ItemInput>
                  <Input
                    type="password"
                    name="password"
                    autoComplete="current-password"
                    onChange={(e) => this.handlePassword(e.target.value)}
                  ></Input>
                </ItemInput>
                <Button>Submit</Button>
              </List>
            </Form>
            <div
              style={{
                position: "absolute",
                visibility: "hidden",
                opacity: "0",
                pointerEvents: "auto",
              }}
            >
              <ReCAPTCHA
                ref={this.captchaRef}
                size="invisible"
                sitekey={global.config.captcha.key}
                data-callback="callback"
                onErrored={(e) => this.handleCaptchaError(e)}
                //onExpired={}
              />
            </div>
          </React.Fragment>
        );
      }
    }

  [1]: https://i.stack.imgur.com/qUqmd.png

**Comment by anl331** [comment]
Im currently running into this issue myself.  Works perfect on desktop but not on mobile.

**Comment by brsnik** [comment]
> Im currently running into this issue myself. Works perfect on desktop but not on mobile.

So the problem was that the local IP I was using was not whitelisted in the ReCaptcha admin panel.

**Comment by anl331** [comment]
Indeed it was, I figured it out as well and that was the issue. Thanks for
the update.
