### ISSUE TITLE
How to change the text content I'm not a robot to I'm a human in reCAPTCHA

### ISSUE THREAD

**Issue by saikrishnabanda5** [dozoisch/react-google-recaptcha#241]

**Comment by dozoisch** [comment]
If there's no option in Google reCAPTCHA, then we can't change it. Is there a specific property in the reCAPTCHA documentation allowing this?

**Comment by IvanAdmaers** [comment]
There is no official API to do this. As I know only hCaptcha has the text “I am human” by default.
