### ISSUE TITLE
ReCaptcha is appearing at the top of the page

### ISSUE THREAD

**Issue by flaviojoaofelix** [dozoisch/react-google-recaptcha#256]
react-google-recaptcha version: 2.1.0
react-async-script version: NA
react: 18.2.0

Hi
I'm trying to use the component on my site along with EmailJS, but it is totally out of alignment , appearing at the top of the page. Does anyone know a solution?

Example:
![Captura de tela de 2022-09-20 22-49-12](https://user-images.githubusercontent.com/99971950/191396130-c79e824f-9f5a-41c0-b171-7554afc6c498.png)

Right Place:
![Captura de tela de 2022-09-20 22-50-37](https://user-images.githubusercontent.com/99971950/191396256-f61a547f-270e-4ed1-847b-91cbbea082c6.png)

My Code:
![Captura de tela de 2022-09-20 22-51-29](https://user-images.githubusercontent.com/99971950/191396351-64e55ffa-2fe5-443d-b2cb-5ab6d1d800ff.png)

Could anyone help me?
Thanks!

**Comment by flaviojoaofelix** [comment]
Hi!
I ended up finding it to be an error in my own CSS.

Sorry for the inconvenience!

**Comment by IlijaRad** [comment]
@flaviojoaofelix Do you remember what it was exactly?
