### ISSUE TITLE
Callback on ready?

### ISSUE THREAD

**Issue by maps82** [dozoisch/react-google-recaptcha#26]
Hi!

Is there any easy way to execute a callback function when the recaptcha is loaded and ready?

**Comment by dozoisch** [comment]
Hi!

There is a hook for the script onload that you can pass as a prop on the component called `asyncScriptOnLoad` (which comes from react-async-script). So technically when the script is loaded the captcha is "ready". There is no other hook that google provide, that we can hook on.
