### ISSUE TITLE
Error: Cannot read properties of undefined (reading 'prototype') in next js 13 app dir

### ISSUE THREAD

**Issue by tarifalhasan** [dozoisch/react-google-recaptcha#274]
react-google-recaptcha version: X.X.X
react-async-script version: Y.Y.Y
![image](https://github.com/dozoisch/react-google-recaptcha/assets/92237522/e912fe3a-c6cb-4f6e-b3b1-506bf83575ef)

**Comment by tarifalhasan** [comment]
import React from 'react';
import ReCAPTCHA from 'react-google-recaptcha';
import dynamic from 'next/dynamic';

const Form = () => {
  function onChange(value) {
    console.log('Captcha value:', value);
  }

  return (
    <div>
      <h2 className=" heading">Contact Us</h2>
      <form action="#" className=" space-y-12">
        <div className=" flex flex-col  gap-y-[-10px]">
          <label
            htmlFor="full_name"
            className=" font-quicksant text-black font-light text-sm sm:text-lg"
          >
            Full Name
          </label>
          <input
            className="  border-b border-black text-black text-sm  sm:text-base font-quicksant focus:outline-none  "
            type="text"
            name="full_name"
            id="full_name"
          />
        </div>
        <div className=" flex flex-col  gap-y-[-10px]">
          <label
            htmlFor="email"
            className=" font-quicksant text-black font-light text-sm sm:text-lg"
          >
            Email
          </label>
          <input
            className="  border-b border-black text-black text-sm  sm:text-base font-quicksant focus:outline-none  "
            type="email"
            name="email"
            id="email"
          />
        </div>
        <div className=" flex flex-col  gap-y-[-10px]">
          <label
            htmlFor="full_name"
            className=" font-quicksant text-black font-light text-sm sm:text-lg"
          >
            Message
          </label>
          <textarea
            className=" h-[50px]  border-b border-black text-black text-sm  sm:text-base font-quicksant focus:outline-none  "
            name="full_name"
            id="full_name"
          />
        </div>
        <ReCAPTCHA
          sitekey="6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI"
          onChange={onChange}
        />
        ,
        <button
          type="submit"
          className="bg-[#02726F] px-10 text-white  py-2.5 rounded-full font-normal font-quicksant text-lg"
        >
          Submit
        </button>
      </form>
    </div>
  );
};

export default Form;

**Comment by tarifalhasan** [comment]
`import React from 'react';
import ReCAPTCHA from 'react-google-recaptcha';
import dynamic from 'next/dynamic';

const Form = () => {
  function onChange(value) {
    console.log('Captcha value:', value);
  }

  return (
    <div>
      <h2 className=" heading">Contact Us</h2>
      <form action="#" className=" space-y-12">
        <div className=" flex flex-col  gap-y-[-10px]">
          <label
            htmlFor="full_name"
            className=" font-quicksant text-black font-light text-sm sm:text-lg"
          >
            Full Name
          </label>
          <input
            className="  border-b border-black text-black text-sm  sm:text-base font-quicksant focus:outline-none  "
            type="text"
            name="full_name"
            id="full_name"
          />
        </div>
        <div className=" flex flex-col  gap-y-[-10px]">
          <label
            htmlFor="email"
            className=" font-quicksant text-black font-light text-sm sm:text-lg"
          >
            Email
          </label>
          <input
            className="  border-b border-black text-black text-sm  sm:text-base font-quicksant focus:outline-none  "
            type="email"
            name="email"
            id="email"
          />
        </div>
        <div className=" flex flex-col  gap-y-[-10px]">
          <label
            htmlFor="full_name"
            className=" font-quicksant text-black font-light text-sm sm:text-lg"
          >
            Message
          </label>
          <textarea
            className=" h-[50px]  border-b border-black text-black text-sm  sm:text-base font-quicksant focus:outline-none  "
            name="full_name"
            id="full_name"
          />
        </div>
        <ReCAPTCHA
          sitekey="6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI"
          onChange={onChange}
        />
        ,
        <button
          type="submit"
          className="bg-[#02726F] px-10 text-white  py-2.5 rounded-full font-normal font-quicksant text-lg"
        >
          Submit
        </button>
      </form>
    </div>
  );
};

export default Form;
`

**Comment by tarifalhasan** [comment]
sorry i forget to write "use client"

**Comment by josef5** [comment]
this helped me
