### ISSUE TITLE
Uncaught DOMException: Blocked a frame with origin "https://www.google.com" from accessing a cross-origin frame.

### ISSUE THREAD

**Issue by shaikh-kamran** [dozoisch/react-google-recaptcha#278]
I have integrated recaptcha in vite-react-ts app and created the build of that. Now i am trying to load that using script tag in other app. I am getting the error
`
Uncaught DOMException: Blocked a frame with origin "https://www.google.com" from accessing a cross-origin frame.
` 
I am running the app locally using http-server with ssl
I have whitelisted localhost in re captcha dashboard
 
react-google-recaptcha version: 3.1.0

**Comment by mockey-jockey** [comment]
Any update on this am also facing same issue

**Comment by shaikh-kamran** [comment]
Yeah, there is no way we can do this, its not allowed to access from cross origin, so i went with reCAPTCHA v3

**Comment by mockey-jockey** [comment]
how did u achieve this in reCAPTCHA v3 can u pls share some sample scripts,
My requirement is to load reCAPTCHA inside the shadow root, once I added am getting the same error.

**Comment by shaikh-kamran** [comment]
I simply followed https://developers.google.com/recaptcha/docs/v3, just make sure you have your own api endpoint in which you verify the token from google api

**Comment by shaikh-kamran** [comment]
Its not allowed to access from cross origin, so i went with reCAPTCHA v3
