### ISSUE TITLE
Warning: Unknown prop `render` on div tag.

### ISSUE THREAD

**Issue by faseidl** [dozoisch/react-google-recaptcha#28]
The following warning in generated when rendering a ReCAPTCHA component:
`Warning: Unknown prop 'render' on div tag. Remove this prop from the element.`

Debugging the distributed code, the root cause is line 108 in the react-google-recaptcha’s recaptcha.js file: 
`return _react2["default"].createElement("div", _extends({}, childProps, { ref: "captcha" }));`

Here, the childProps contain a “render” property which is inappropriate for a div element.

A patch is to exclude "render" from the childProps just above by adding “render” to the list of excluded props:
`var childProps = _objectWithoutProperties(_props, ["render", "sitekey", "onChange", "theme", "type", "tabindex", "onExpired", "size", "stoken", "grecaptcha”]);`

In the original recaptcha.js source (pre-webpack), this fix translates to also consuming ‘render’ on line 80:
`const{render,sitekey,onChange,theme,type,tabindex,onExpired,size,stoken,grecaptcha,...childProps}=this.props;`

**Comment by dozoisch** [comment]
I'm not sure why there is a prop called render though. Can you share how you use the component?

**Comment by faseidl** [comment]
Looking at my usage, I see that the `render` attribute is set to "explicit" in my code. Not sure if that's really necessary--I grabbed that usage from an example somewhere.

```
import React from 'react';
import ReCAPTCHA from 'react-google-recaptcha';

import {RECAPTCHA_SITE_KEY} from '../conf/app_config';

class Captcha extends React.Component {

    render() {
        const {input, meta} = this.props;
        return (
            <fieldset className='form-group'>
                <ReCAPTCHA
                    sitekey={RECAPTCHA_SITE_KEY}
                    render="explicit"
                    size="normal"
                    onChange={input.onChange}/> 
                    {meta.touched && meta.error && <div className='alert alert-danger'>{meta.error}</div>}
            </fieldset>
        );
    }
}

Captcha.propTypes = {
    input: React.PropTypes.object,
    meta: React.PropTypes.object
};

export default Captcha;
```

**Comment by dozoisch** [comment]
This prop is not consumed by react-google-recaptcha so it's not needed! Removing it should lead to the same result as before without the warning.

See [the list of props used](https://github.com/dozoisch/react-google-recaptcha/blob/master/src/recaptcha.js#L5-L15).

**Comment by faseidl** [comment]
Thanks!
