### ISSUE TITLE
Possible to support http to avoid browser error?

### ISSUE THREAD

**Issue by babsonmatt** [dozoisch/react-google-recaptcha#3]
Currently using recaptcha on an http page which is generating the following error:

```
Uncaught SecurityError: Blocked a frame with origin "https://www.google.com" from accessing a frame with origin "http://local:3001".  The frame requesting access has a protocol of "https", the frame being accessed has a protocol of "http". Protocols must match.
```

**Comment by dozoisch** [comment]
Humm... Well you can not load reCaptcha without https, https://developers.google.com/recaptcha/docs/display#auto_render

**Comment by babsonmatt** [comment]
Ah interesting.  Despite the above error everything seems to run fine.
