### ISSUE TITLE
reCaptcha v2 not returning value

### ISSUE THREAD

**Issue by mbasakCinedigmInd** [dozoisch/react-google-recaptcha#300]
react-google-recaptcha version: 3.1.0
react-async-script version: 1.2.0

i included recaptcha v2 in my code but after the tick its not giving the value but

**anchor:1 Uncaught (in promise) TypeError
bframe:1 Uncaught (in promise) TypeError**

my code: 
import ReCAPTCHA from "react-google-recaptcha";
<ReCAPTCHA
    sitekey={ConVar.V2sitekey.key}
    onChange={captchaClicked}
  />

**Comment by zachpang** [comment]
experiencing the same issue

**Comment by mbasakCinedigmInd** [comment]
@zachpang i found a rendering issue on my code. recpatcha should be rendered when the page render. it should not depend on any state. that is how my issue got solved, hope it helps
