### ISSUE TITLE
UNMET PEER DEPENDENCY

### ISSUE THREAD

**Issue by olegreznichenko** [dozoisch/react-google-recaptcha#31]
After 0.6.0 releas.
react-google-recaptcha@0.6.0 requires a peer of react-async-script@~0.6.0 || ~0.7.0 but none was installed.

**Comment by adriantoine** [comment]
Yeah and building my code gives this error:
```
ERROR in ./~/react-google-recaptcha/lib/recaptcha-wrapper.js
Module not found: Error: Can't resolve 'react-async-script' in '/Users/adrien/Projects/tray/website/node_modules/react-google-recaptcha/lib'
 @ ./~/react-google-recaptcha/lib/recaptcha-wrapper.js 9:24-53
 @ ./website/src/components/SignupForm/component.js
 @ ./website/src/components/SignupForm/index.js
 @ ./website/src/views/Signup/component.js
 @ ./website/src/views/Signup/index.js
 @ ./website/src/routes.js
 @ ./website/src/entry.js
 @ ./website/src/client.bootstrap.js
 @ multi webpack-hot-middleware/client?path=http://localhost:3000/__webpack_hmr ./website/src/client.bootstrap
```

The issue is just to install `react-async-script` with npm, I think it should be added to the README though.

**Comment by dozoisch** [comment]
I'll add it to readme. Although the NPM error is pretty well worded for peer dependency.

**Comment by adriantoine** [comment]
Yeah it is, but it's better to install everything at once rather than running into errors.

Thanks!

**Comment by dozoisch** [comment]
@adriantoine It was removed from being a dependency because it created some issues. Although I agree!
