### ISSUE TITLE
Loaded notification

### ISSUE THREAD

**Issue by Sawtaytoes** [dozoisch/react-google-recaptcha#33]
I want to show a loading indicator while it's in the process of loading so people know they can do anything yet. Is there a way to added a notification `onLoaded` for when the reCAPTCHA's loaded?

**Comment by dozoisch** [comment]
You should be able to pass a function as prop `asyncScriptOnLoad` (needs to be documented on this repo, but it's a prop of https://github.com/dozoisch/react-async-script) and that should be called when the JavaScript for recaptcha is loaded

**Comment by Sawtaytoes** [comment]
Thanks! That fixed it for me. It seems to call early once I've loaded the page already and swap components using component state and `{this.state.isVisible && <SomeComponent />}`. What happens is I'll click a link and show `<ReCAPTCHA>` again, but the second time it loads, it instantly calls `asyncScriptOnLoad` even before I've seen it load. Strangely, it also loads a lot faster than when I load the page fresh.

This could very well be something in my code though.

**Comment by dozoisch** [comment]
Well, the second time, technically the script is already loaded, so the component should load pretty fast. Google only provides a callback on the script load, and since it's already loaded the second time I call the callback right away.
