### ISSUE TITLE
react-async-script shown in the docs, but unnecessary from use

### ISSUE THREAD

**Issue by Sawtaytoes** [dozoisch/react-google-recaptcha#42]
Looks like the docs show `react-async-script` being a necessary part of the installation, but seems necessary based on the fact that you can put a prop `asyncScriptOnLoad={onLoad}` on the ReCAPTCHA component itself.

**Comment by dozoisch** [comment]
@Sawtaytoes react-async-script is a peer. It's used internally, it used to be a dependency but someone requested to make it just a peer dependency, so it has to be installed manually.

**Comment by sebmor** [comment]
To be honest if it is used internally it makes sense to be a dependency

**Comment by dozoisch** [comment]
@sebmor People we're using it for other things in their project and it being a dep instead of peer was causing version issues.

**Comment by NathanielHill** [comment]
Seems like it's pretty clearly a direct dependency. I suspect you've solved a problem for a handful of noisy users while inconveniencing a much larger group of silent users. NPM and Yarn should both be able to handle multiple versions, I suspect you solved someone else's bug by breaking the dependency tree.
