### ISSUE TITLE
Render function issue

### ISSUE THREAD

**Issue by stevematdavies** [dozoisch/react-google-recaptcha#44]
Using in side React 15+

Following error is thrown whenever the component is used:

Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.

**Comment by newyork-anthonyng** [comment]
@stevematdavies Could you include a code snippet that reproduces this warning?

**Comment by stevematdavies** [comment]
Follow the instructions as given. However , it appears the problem can be circumvented by importing rather than requiring the component. However it does then mean it can't be a composite component .

Sent from my Windows 10 phone

**Comment by dozoisch** [comment]
@stevematdavies Might be an issue with es6 export compates. So instead of `require('react-google-recaptcaha')` do require('react-google-recaptcha').default` for now.

I'll check to make sure we are exporting in compatibility with require.

**Comment by newyork-anthonyng** [comment]
@dozoisch 

We could add something like this to the bottom of the `recaptcha-wrapper.js` file. I can make a PR if it looks good.

```jsx
// recaptcha-wrapper.js
const ReCAPTCHAWrapper = makeAsyncScriptLoader(ReCAPTCHA, URL, {
  callbackName,
  globalName,
  exposeFuncs: ["getValue", "reset", "execute"],
});

if (typeof module !== 'undefined' && module.exports) {
  module.exports = ReCAPTCHAWrapper;
}

export default ReCAPTCHAWrapper;
```

With this code snippet, the following would both work
```js
import ReCAPTCHA from 'react-google-recaptcha';
// or
const ReCAPTCHA = require('react-google-recaptcha');
```

**Comment by dozoisch** [comment]
I'm hesitating between: https://github.com/59naga/babel-plugin-add-module-exports. Or just updating the doc to specify `require().default;` since that is more in line with the spec.
