### ISSUE TITLE
TypeError: Cannot read property 'value' of null when navigating back and forth with react-router

### ISSUE THREAD

**Issue by danielkhan** [dozoisch/react-google-recaptcha#45]
I am running into the problem described here: https://gedgei.wordpress.com/2015/08/07/using-recaptcha-in-single-page-applications/
Is there a way to retrieve the widget id for a given component to use it in getResponse() then?

**Comment by dozoisch** [comment]
It's already technically passing the widget id in the setReponse (https://github.com/dozoisch/react-google-recaptcha/blob/master/src/recaptcha.js#L13) but I guess the state gets reset. I could setup a method to expose getting the id, but I'm not sure how it could be used afterwards

**Comment by danielkhan** [comment]
Do you see a change to get this by passing in the recaptcha object in? The thing is that I need a reference to this one recaptcha in the current component.

**Comment by danielkhan** [comment]
I found a solution:

```js
// Recaptcha.js
import React, {Component} from "react";
import ReCaptcha from 'react-google-recaptcha';
class Recaptcha extends Component {
  constructor(props) {
    super(props);
  }
  componentDidMount() {
    this.props.setRecaptcha(this._recaptcha);
  }

  render() {
    return (
      <div>
        <ReCaptcha
          ref={(recaptcha) => { this._recaptcha = recaptcha; }}
          sitekey={window.RECAPTCHA_SITE_KEY}
          onChange={this.props.onChange}
        />
      </div>
    )
  }
}
export default Recaptcha
```

```js
// parent.js

setRecaptcha(recaptcha) {
     this.setState({recaptcha: recaptcha});

    // Subsequently tge widgetId can be found in
   this.state.recaptcha.childComponent.state.widgetId
}

// render()
<Recaptcha id="recaptchaRelease" setRecaptcha={this.setRecaptcha.bind(this)} onChange={this.verifyCallback.bind(this)}/>
```
