### ISSUE TITLE
Any way to get widgetid?

### ISSUE THREAD

**Issue by m-orsh** [dozoisch/react-google-recaptcha#52]
With the standard google api we can use widgetid = grecaptcha.render(params). Having the widgetid allows us to specify which widget to execute recaptcha on. For example, if the user has a modal window that can be opened/closed and reopened, if the widget is loaded a second time when the user opens the modal a second time, there won't be a way of interacting with that specific recaptcha widget unless we have the widgetid.

**Comment by dozoisch** [comment]
I'd be open for a pr that adds an accessor on the captcha like getWidgetId as the captcha component has the id in its state right now.

else I'll try to add it when I get some time.

**Comment by m-orsh** [comment]
made a PR for an accessor

**Comment by dozoisch** [comment]
Thanks! Merged, I'll cut a release asap

**Comment by m-orsh** [comment]
remember to add the new accessor to readme.md

**Comment by dozoisch** [comment]
Oh true.
