### ISSUE TITLE
recaptcha error render

### ISSUE THREAD

**Issue by dieuit07** [dozoisch/react-google-recaptcha#54]
react 15.03
react-google-recaptcha 0.8.1

in my file: 
```
const ReCAPTCHA = require('react-google-recaptcha/lib/recaptcha')


render() {
  <div className="login">
    ...
    <ReCAPTCHA ref="recaptcha"
                                  size="normal"
                                  onChange={(e) => this.test(e)}
                                  sitekey="[SITE_KEY]"/>
  </div>
}
```

the error: 
```
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render 
```

Did I miss some config or It have to render by any special way?

**Comment by dozoisch** [comment]
Might have to do `const ReCAPTCHA = require('react-google-recaptcha/lib/recaptcha').default`

If you import with require. Otherwise 

`import ReCAPTCHA from 'react-google-recaptcha/lib/recaptcha';`

should work

**Comment by dieuit07** [comment]
The error 's gone away but it render just: "<div></div>"

**Comment by sepler** [comment]
@dieuit07 

`import ReCAPTCHA from 'react-google-recaptcha/lib/recaptcha-wrapper';`

**Comment by stevematdavies** [comment]
Doesn't your render function need a return statement?

```
render(){
    return(
    .....  
   );
}
```

**Comment by dieuit07** [comment]
Sure stevematdavies. Still not work, I have moved to other lib. Thanks Guys
