### ISSUE TITLE
Use this for RN app

### ISSUE THREAD

**Issue by DavitVosk** [dozoisch/react-google-recaptcha#56]
Hey. Thanks for your works. 

Can you please advise whether this repo can be used for react-native apps?

**Comment by dozoisch** [comment]
If you render it inside a webview it could work, but the recaptcha script used is only compatible with the web right now.

**Comment by DavitVosk** [comment]
ok thanks. Do you know other option to use captcha in RN apps?

**Comment by dozoisch** [comment]
I have never looked into it unfortunately!

**Comment by DavitVosk** [comment]
ok thanks for your time @dozoisch
