### ISSUE TITLE
Recaptcha Doesn't load on first render

### ISSUE THREAD

**Issue by stevematdavies** [dozoisch/react-google-recaptcha#58]
Using a Recapture in a rendered page, wont always load the Recaptcha box when react.render is fired, only refreshing the page or firing render again works. 

Console also warns `ReCAPTCHA couldn't find user-provided function: onloadcallback`

Since this is a wrapper for react, should this not working in relation to reacts lifecycle functions, there is no way to hold up render() (nor would one want to) how can we overcome this issue?

Im rendering as below; (onChange fires an imported redux action).

```
const  ReCaptchaBox => ({dispatch}) => (
<ReCAPTCHA
    sitekey={AppProperties.googleReCaptchaKey}
    size="normal"
    onChange={r => sendRecaptchaVerificationRequest(dispatch, r)}/>);
....
```

Once the ReCaptcha is loaded, it works fine despite the warning, but it simply wont render the first time if the element is a child of another element, or inside a render function. For example, a partial of where I am using my component looks as follows:
```
<form>
        ....
        <ReCaptchaBox/>
        ....
</form>
```

**Comment by stevematdavies** [comment]
Seems this issue can be fixed by including the script call to google recaptcha in html, this should be mentioned in the documentation

**Comment by dozoisch** [comment]
This should normally be needed as it's supposed to load the script by itself.

**Comment by dozoisch** [comment]
From the param you are sending vs what I have in the code, it seems it changed.

See https://github.com/dozoisch/react-google-recaptcha/blob/master/src/recaptcha-wrapper.js#L8

Where I;m passing onload. If locally you changed the url to use onloadcallback instead of onload does it work?

**Comment by stevematdavies** [comment]
No it doesn't, it still throws the warning, and the api for this react component, doesn't specify an onload or onloadcallbackparameter, and doesn't fix the issue in itself.

AS I said, I solved it by including a call to the google script itself in my html, but this is not clearly instructed in the docs

**Comment by dozoisch** [comment]
Yes, because you are not supposed to need to.

**Comment by stevematdavies** [comment]
I assumed the same, especially since the documentation does not require it. , but none the less as it stands now, it works. Perhaps its a bug?

**Comment by dozoisch** [comment]
Yes, it what I'm wondering is that maybe googlechanged the API because talks about an "onloadcallback" instead of "onload". I'll try to investigate whenever I have time

**Comment by stevematdavies** [comment]
Great!, it seems to be more what Google are expecting in changing the gloaposts as usual!  I will keep watching for updates. Many thanks for the help.

**Comment by stevematdavies** [comment]
Actually looking at your code here, it already seems correct.

**Comment by dozoisch** [comment]
Let me know if you stumble on anything. The easiest way is to figure out what callback name is being passed by react-async-script (the hoc component being used) and logging to make sure the callback is defined properly on the window!

**Comment by meadow-tulips** [comment]
The problem which I am facing is siteKey is coming from props from an API call, and there is a delay in that. The DOM gets painted and hence it always says invalid Site Key even though I can console.log the key value which is fine. If I hard code the key value. it works fine.
