### ISSUE TITLE
Cant set language with global variable

### ISSUE THREAD

**Issue by toti1212** [dozoisch/react-google-recaptcha#62]
Hi,
I tried to set the Spanish language in index.js for an app created by create-react-app.
`window.recaptchaOptions = {
  lang: 'es'
};`

The captcha still load in English language. Any suggestions? Thnks!

**Comment by toti1212** [comment]
OK, i tried to set this in the index.html in a <script> and does it work.

**Comment by dozoisch** [comment]
@toti1212 glad it worked!
