### ISSUE TITLE
ReCAPTCHA couldn't find user-provided function: onloadcallback

### ISSUE THREAD

**Issue by amalv** [dozoisch/react-google-recaptcha#63]
I'm trying to migrate our current recaptcha implementation in order to use this dependency instead of `react-captcha` (since it doesn't seem to support invisible recaptcha).

Here is part of the implementation using `react-captcha` dependency (which works perfectly fine):

```
<Recaptcha
  ref={ref => (this.recaptchaInstance = ref)}
  sitekey={params.captcha.key}
  render="explicit"
  verifyCallback={this.validateCaptchaResponse}
  onloadCallback={this.captchaCallback}
  expiredCallback={this.captchaExpired}
/>
```

And here is the `react-google-recaptcha` implementation (which gives the user-provided function error message):

![recaptcha](https://user-images.githubusercontent.com/1252707/32669366-92e139da-c640-11e7-9111-2f2b30d2e4ff.png)

```
<ReCAPTCHA
  ref={ref => (this.recaptchaInstance = ref)}
  size="invisible"
  sitekey={params.captcha.key}
  onExpired={this.captchaExpired}
  onChange={this.validateCaptchaResponse}
/>
```

It seems the problem is related to the missing `onloadCallback` function, I've also tried using the same function `onloadCallback` as the original `react-recaptcha` implementation without success and I didn't see any equivalent `onloadCallback` prop in the `react-google-recaptcha` documentation. Any suggestions?

**Comment by dozoisch** [comment]
@amalv how are you loading the script? The captcha normally loads the script by itself (using react-async-script, and specifies the callback here: https://github.com/dozoisch/react-google-recaptcha/blob/master/src/recaptcha-wrapper.js#L4). Async-script then sets the callback by himself here: https://github.com/dozoisch/react-async-script/blob/master/src/async-script-loader.js#L72-L74.

**Comment by amalv** [comment]
You are right, a duplication loading the script was causing the problem. Thanks for the help!
