### ISSUE TITLE
Issue installing with yarn

### ISSUE THREAD

**Issue by Amin52J** [dozoisch/react-google-recaptcha#68]
When installing with `yarn` v1.3.2 `react-async-script` which is in peerDependencies in the package.json doesn't get installed. It works fine with `npm`. I think the solution would be to change the peerDependencies in the package.json to dependencies.

**Comment by dozoisch** [comment]
@Amin52J peer dependencies change was made because some one asked about that. All you have to do is run `yarn add react-async-script`
