### ISSUE TITLE
Can't resize responsively

### ISSUE THREAD

**Issue by Lian1230** [dozoisch/react-google-recaptcha#69]
Trying to giving the 'size' property different value base on the window size, so it can be responsive.
Seems like it only uses the initial value. Can't switch between 'compact' and 'normal' when the window size changes.

**Comment by dozoisch** [comment]
@Phuhwei I don't think prop cause a remove&rerender of the captcha. I'm open to prs to do so.

**Comment by slaponicus** [comment]
I use this with [react-responsive](https://github.com/contra/react-responsive) and it works great. Just wrap the ReCAPTCHA in a MediaQuery and it will be re-rendered when the viewport size change to a different breakpoint.

**Comment by Avatoz** [comment]
Hey @dozoisch, would like to know if the best approach is to keep using react-responsive on top of it, or if the feature is already in place.

**Comment by RezaRahmati** [comment]
Neither solutions worked for me

```
 const isMobile = useMediaQuery({ query: '(max-width: 767px)' })
 
 ...
    <div className="col-sm-6 form-group">
        IsMobile: {JSON.stringify(isMobile)}
        {isMobile ?
            <>
                Compact
                <ReCAPTCHA
                    size="compact"
                    hl='fa'
                    ref={recaptchaRef}
                    sitekey={process.env.NEXT_PUBLIC_RECAPTCHA_SITE_KEY ?? ''}
                    onChange={(value) => {
                        setFieldValue('recaptcha', value);
                    }}
                />
            </>
            :
            <>
                Normal
                <ReCAPTCHA
                    size="normal"
                    hl='fa'
                    ref={recaptchaRef}
                    sitekey={process.env.NEXT_PUBLIC_RECAPTCHA_SITE_KEY ?? ''}
                    onChange={(value) => {
                        setFieldValue('recaptcha', value);
                    }}
                />
            </>
        }

    </div>
```

![captcha](https://user-images.githubusercontent.com/10086092/163515197-79d714de-61a6-4182-bd3d-3f3b82afa11f.gif)

**Comment by craigstowers-guroo** [comment]
Hey @RezaRahmati
I know this is an old thread, but react won't re-render any change as it doesn't notice any DOM change (it probably ignores all the stuff inside an iframe). You can force a re-render by giving each component a unique key. 

` <div className="col-sm-6 form-group">
        IsMobile: {JSON.stringify(isMobile)}
        {isMobile ?
            <>
                Compact
                <ReCAPTCHA
                    size="compact"
                    key="recaptcha-compact"
                    hl='fa'
                    ref={recaptchaRef}
                    sitekey={process.env.NEXT_PUBLIC_RECAPTCHA_SITE_KEY ?? ''}
                    onChange={(value) => {
                        setFieldValue('recaptcha', value);
                    }}
                />
            </>
            :
            <>
                Normal
                <ReCAPTCHA
                    size="normal"
                    key="recaptcha-normal"
                    hl='fa'
                    ref={recaptchaRef}
                    sitekey={process.env.NEXT_PUBLIC_RECAPTCHA_SITE_KEY ?? ''}
                    onChange={(value) => {
                        setFieldValue('recaptcha', value);
                    }}
                />
            </>
        }

    </div>`

**Comment by plaibo1** [comment]
Its work for me.
`
<ReCAPTCHA
              key={isMobile ? "compact-recaptcha" : "normal-recaptcha"}
              sitekey={API_RECAPTCHA_V2_KEY}
              ref={captchaRef}
              size={isMobile ? "compact" : "normal"}
              type="image"
              onChange={() => setIsEmptyCaptcha(false)}
              onError={() => setIsEmptyCaptcha(true)}
            />
`

**Comment by plaibo1** [comment]
Its work for me
`<ReCAPTCHA
              key={isMobile ? "compact-recaptcha" : "normal-recaptcha"}
              sitekey={API_RECAPTCHA_V2_KEY}
              ref={captchaRef}
              size={isMobile ? "compact" : "normal"}
              type="image"
              onChange={() => setIsEmptyCaptcha(false)}
              onError={() => setIsEmptyCaptcha(true)}
            />`
