### ISSUE TITLE
Cannot contact reCAPTCHA. Check your connection and try again.

### ISSUE THREAD

**Issue by ionutcirja** [dozoisch/react-google-recaptcha#70]
Hi,

I'm not sure if this is related to this library or is just a google thingie.

I have a login form (redux form) with a recaptcha field (using the invisible one).
When I'm executing captcha for the first time, everything is ok and form will be submitted.
In case of wrong username or password, when I will execute it for the second time, a popup comes and says: 'Cannot contact reCAPTCHA. Check your connection and try again.'.
If I will execute captcha again, now it works and the iframe with the images is displayed.

Any idea?

Thanks for you help,

**Comment by matviishyn** [comment]
Remove current REcaptcha key, then register new key and set your **key settings** with domains:
```
127.0.0.1
localhost
```

**Comment by ionutcirja** [comment]
It seems for single page apps we have to reset the captcha also and not just execute it.
