### ISSUE TITLE
Can't force focus on recaptcha

### ISSUE THREAD

**Issue by djshapiro** [dozoisch/react-google-recaptcha#71]
For accessibility, I need to be able to focus on the checkbox when the user attempts to submit the form while not being validated. I currently see no way to do that with your component. Ideally, I'd be able to call `this.recaptcha.focus()`, where `this.recaptcha` is the ref.

**Comment by dozoisch** [comment]
Does recaptcha has a focus function? If yes, it can easily be exposed (just like the reset).

**Comment by djshapiro** [comment]
Google recaptcha does not appear to support taking focus on command.
