### ISSUE TITLE
Possible to add Challenge Cancelled Event?

### ISSUE THREAD

**Issue by fluffy-samurai** [dozoisch/react-google-recaptcha#74]
Would it be possible to add a functionality akin to `onChange` or `onExpired`, but for when a user clicks out of a ReCaptcha Challenge?

**Comment by dozoisch** [comment]
Hi @fluffy-samurai, Google reCAPTCHA doesn't expose any parameters for this in their api, and so it's not possible (see https://developers.google.com/recaptcha/docs/display?authuser=2#render_param).

This is just a wrapper on reCAPTCHA and so can not support any feature not supported by upstream library.
