### ISSUE TITLE
this.props.grecaptcha.render is not a function

### ISSUE THREAD

**Issue by OakSupanat** [dozoisch/react-google-recaptcha#79]
I have used the react-google-recaptcha for a while and it used to work well.
But recently, I found that there's a bug with the following error log,

```Uncaught (in promise) TypeError: this.props.grecaptcha.render is not a function```

![image](https://user-images.githubusercontent.com/16416627/39691601-42ec5492-5208-11e8-9001-4af84f5c8b32.png)

Not sure if someone encounters the bug as mine.
And my website is a Single Page Application (SPA) implemented in React framework.

**Comment by joshuaalpuerto** [comment]
@OakSupanat this is related with issue #76

**Comment by dozoisch** [comment]
#78 has been merged

**Comment by RazaHussayn** [comment]
@OakSupanat   let googleCaptcha = "";
    googleCaptcha = window.recaptcha ? (
      <div className="form-group" style={{ textAlign: "left" }}>
        <ReCaptcha
          ref={el => {
            this.captchaDemo = el;
          }}
          size="normal"
          data-theme="dark"
          render="explicit"
          sitekey="6Lc0grgUAAAAAOwsCXgRnfCajVxtyddV5sPHvACW"
          onloadCallback={this.onLoadRecaptcha}
          verifyCallback={this.verifyCallback}
          hl={string.LANGUAGE}
        />
      </div>
    ) : (
      ""
    );

**Comment by RazaHussayn** [comment]
@OakSupanat 


 let googleCaptcha = "";
    googleCaptcha = window.recaptcha ? (
      <div className="form-group" style={{ textAlign: "left" }}>
        <ReCaptcha
          ref={el => {
            this.captchaDemo = el;
          }}
          size="normal"
          data-theme="dark"
          render="explicit"
          sitekey="6Lc0grgUAAAAAOwsCXgRnfCajVxtyddV5sPHvACW"
          onloadCallback={this.onLoadRecaptcha}
          verifyCallback={this.verifyCallback}
          hl={string.LANGUAGE}
        />
      </div>
    ) : (
      ""
    );

**Comment by RazaHussayn** [comment]
@OakSupanat 


 let googleCaptcha = "";
    googleCaptcha = window.recaptcha ? (
      <div className="form-group" style={{ textAlign: "left" }}>
        <ReCaptcha
          ref={el => {
            this.captchaDemo = el;
          }}
          size="normal"
          data-theme="dark"
          render="explicit"
          sitekey="Your Key"
          onloadCallback={this.onLoadRecaptcha}
          verifyCallback={this.verifyCallback}
          hl="en"
        />
      </div>
    ) : (
      ""
    );
