### ISSUE TITLE
NPM Release for v0.11.1

### ISSUE THREAD

**Issue by mertkahyaoglu** [dozoisch/react-google-recaptcha#80]
Hi everyone. Thanks so much for this package. We are using v0.11.0 @iyzico and recently experiencing #76. I saw that this issue has been fixed but npm package has not been updated yet. Is it possible to publish a new release for npm?

**Comment by dozoisch** [comment]
@mertkahyaoglu v0.11.1 has bee published! Sorry about that.

**Comment by mertkahyaoglu** [comment]
Thank you @dozoisch 🎉
