### ISSUE TITLE
How to check if the response is successfull

### ISSUE THREAD

**Issue by johhansantana** [dozoisch/react-google-recaptcha#93]
I know you can have something like this:

```js
const onChange = response => {
  console.log("response: ", response);
};
```

It prints out a long string when success but what's the response when it fails?

**Comment by hartzis** [comment]
adding to #91 :)

**Comment by hartzis** [comment]
`"error-callback"` support added to [`1.0.0` release](https://github.com/dozoisch/react-google-recaptcha/blob/master/CHANGELOG.md#v100---fri-17-aug-2018-181100-pst)
