### ISSUE TITLE
`onChange` prop-type is too strict

### ISSUE THREAD

**Issue by ahuth** [dozoisch/react-google-recaptcha#99]
https://github.com/dozoisch/react-google-recaptcha/blob/1ff4eae39762135ed5de36a271eee1dc10dbda85/src/recaptcha.js#L121

My use-case does not involve using `onChange`. Instead I rely on the injected `textarea` node within my form to appropriate structure my parameters. 

I think it would be beneficial to avoid requiring the `onChange` property -- it even works when it is `undefined`.

**Comment by hartzis** [comment]
That seems sensible... and is essentially backwards compatible. Would you like to make a PR?

**Comment by hartzis** [comment]
Should be as "simple":
- remove the `isRequired`
- make a method like `handleOnChange`
  - use new method here: https://github.com/dozoisch/react-google-recaptcha/blob/1ff4eae39762135ed5de36a271eee1dc10dbda85/src/recaptcha.js#L57
  - in new method only call `props.onChange` if exists: `onChange && onChange(data)`
- update tests
- profit 🤑

**Comment by ahuth** [comment]
Sounds good

**Comment by ahuth** [comment]
Resolved in #102
